# Date: 2024-07-12 17:00
# Author: lglaboy
# GitHub: https://github.com/lglaboy
# Description: 检查 /etc/ssh/ssh_config 所有生产环境主机中的配置
# Version: v1.0

# 多线程批量运行 -f 100
- name: init env
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    log_file: /tmp/check_k3s_list.csv
  tasks:
    # 初始化日志文件
    - name: 初始化日志文件
      shell: if [ -f {{ log_file }} ];then mv {{ log_file }} {{ log_file }}_$(date +"%Y_%m_%d_%H_%M_%S");fi
    # 获取主机
    - name: get hosts
      shell: grep -E "Host\s+" /etc/ssh/ssh_config | grep -E -v -i "^#|\*|JENKINS|gitlab|kubevirt|LOCALTEST|LOCAL-DEMO|LOCALDEMO|KR|K3S|K8S|ALIYUN|-DEV-|-TEST|sw|sky|CLOUD|SENTRY" | awk '{print $NF}' | sort
      register: grep_hosts
    # 添加主机到临时主机组
    - add_host:
        name: "{{ item }}"
        group: tmp_hosts
      with_items: "{{grep_hosts.stdout_lines}}"
    # # 输出所有主机组
    # - debug:
    #     var: groups

- name: check k3s middleware config
  hosts: tmp_hosts
  remote_user: swift
  gather_facts: False
  vars:
    log_file: /tmp/check_k3s_list.csv
  tasks:
    - name: 判断是否存在k3s目录
      stat:
        path: /home/swift/k3s-yamls
      register: k3s_path

    - block:
      - name: 存在检查nacos配置
        shell: grep mysqlnacos /home/swift/k3s-yamls/middleware/default/*
        register: grep_out

      - name: 输出不存在结果
        local_action: shell echo "{{ inventory_hostname }},nacos-server,不存在mysqlnacos-mysql" >> "{{ log_file }}"
        when: grep_out.rc != 0
        ignore_errors: true

      - name: 输出存在结果
        local_action: shell echo "{{ inventory_hostname }},nacos-server,存在mysqlnacos-mysql" >> "{{ log_file }}"
        when: grep_out.rc == 0
      when: k3s_path.stat.isdir is defined and k3s_path.stat.isdir

    - name: 不存在，输出结果，退出
      local_action: shell echo "{{ inventory_hostname }},nacos-server,非k3s环境主机" >> "{{ log_file }}"
      when: k3s_path.stat.isdir is undefined