apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-static
  namespace: dba
spec:
  selector:
    matchLabels:
      postgresql: test-static
  serviceName: postgresql-static
  template:
    metadata:
      labels:
        postgresql: test-static
    spec:
      containers:
      - name: postgresql-static
        image: swr.cn-east-2.myhuaweicloud.com/common-server/postgres:1-vim
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: PGDATA
          value: /var/lib/postgresql/data
        ports:
        - name: server
          containerPort: 5432
        resources:
          limits:
            cpu: "200m"
            memory: 8Gi
        volumeMounts:
          - name: data
            mountPath: /data
          - name: varlibpostgresqldata
            mountPath: /var/lib/postgresql/data
          - name: temp
            mountPath: /var/lib/postgresql/temp
          - name: localtime
            mountPath: /etc/localtime
      volumes:
        - name: data
          hostPath:
            path: /opt/project/shardingsphere/postgresql-static/data
        - name: varlibpostgresqldata
          hostPath:
            path: /opt/project/shardingsphere/postgresql-static/varlibpostgresqldata
        - name: temp
          hostPath:
            path: /opt/project/shardingsphere/postgresql-static/temp
        - name: localtime
          hostPath:
            path: /etc/localtime
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        kubernetes.io/hostname: k3s-localtest-005
      priorityClassName: high-priority-4
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-static
  namespace: dba
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.1.123
spec:
  selector:
    postgresql: test-static
  ports:
  - name: server
    port: 5432
    targetPort: server
  type: LoadBalancer
  loadBalancerIP: 192.168.1.123