apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rocketmq-0
  name: rocketmq-0
  namespace: local3-test
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rocketmq-0
  template:
    metadata:
      labels:
        app: rocketmq-0
    spec:
      hostname: localhost
      nodeSelector:
        kubernetes.io/hostname: k3s-localtest-001
      priorityClassName: high-priority-4
      containers:
      - name: rocketmq-namesrv
        env:
        - name: MAX_HEAP_SIZE
          value: "1024M"
        - name: HEAP_NEWSIZE
          value: "256M"
        command:
        - ./mqnamesrv
        image: swr.cn-east-2.myhuaweicloud.com/common-server/rocketmq:4.9.4-custom
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9876
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: "2G"
          requests:
            cpu: "0.1"
            memory: "1G"
        livenessProbe:
          tcpSocket:
            port: 9876
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 60
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 9876
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 60
          periodSeconds: 5
      - name: rocketmq-broker
        env:
        - name: MAX_HEAP_SIZE
          value: "1024M"
        - name: HEAP_NEWSIZE
          value: "256M"
        command:
        - ./mqbroker
        - -c
        - /opt/conf/broker.properties
        - autoCreateTopicEnable=true
        image: swr.cn-east-2.myhuaweicloud.com/common-server/rocketmq:4.9.4-custom
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10909
          name: brokerslave
        - containerPort: 10911
          name: brokerserver
        - containerPort: 10912
          name: brokerconsume
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
        livenessProbe:
          tcpSocket:
            port: 10911
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 60
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 10911
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 60
          periodSeconds: 5
        volumeMounts:
        - mountPath: /root/logs/
          name: logs
        - mountPath: /opt/conf/broker.properties
          name: rocketmq-broker-0-config
          subPath: broker.properties
        - mountPath: /root/store
          name: store
      imagePullSecrets:
        - name: regcred
      volumes:
      - name: logs
        hostPath:
          path: /opt/project/project-middleware/local3-test/broker-0-logs
      - configMap:
          defaultMode: 420
          name: rocketmq-broker-0-config
        name: rocketmq-broker-0-config
      - name: store
        hostPath:
          path: /opt/project/project-middleware/local3-test/broker-0-store
      # tolerations:
      # - key: "app"
      #   operator: "Equal"
      #   value: "alone"
      #   effect: "NoSchedule"
