apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: ${LoadBalancerIP}
  name: nacos-cluster
spec:
  selector:
    app: nacos-cluster
  ports:
    - port: 18848
      name: server
      targetPort: 8848
  type: LoadBalancer
  loadBalancerIP: ${LoadBalancerIP}